### ISSUE TITLE
promax is unavailable

### ISSUE THREAD

**Issue by alex13by** [xinsir6/ControlNetPlus#16]
2024-07-14 10:36:29,165 - ControlNet - INFO - [tile_colorfix.threshold_a] Invalid value(1.0), using default value 8.0.
2024-07-14 10:36:31,704 - ControlNet - INFO - unit_separate = False, style_align = False
2024-07-14 10:36:31,704 - ControlNet - INFO - Loading model: controlnet-union-sdxl-promax [9460e4db]
2024-07-14 10:36:31,937 - ControlNet - INFO - Loaded state_dict from [D:\AI\sd-webui-aki-v4.8\models\ControlNet\SDXL\controlnet-union-sdxl-promax.safetensors]
2024-07-14 10:36:31,946 - ControlNet - INFO - controlnet_sdxl_config
*** Error running process: D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AI\sd-webui-aki-v4.8\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1228, in process
        self.controlnet_hack(p)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1213, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 919, in controlnet_main_entry
        model_net, control_model_type = Script.load_control_model(p, unet, unit.model)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 436, in load_control_model
        control_model = Script.build_control_model(p, unet, model)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 465, in build_control_model
        control_model = build_model_by_guess(state_dict, unet, model_path)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", line 240, in build_model_by_guess
        network = PlugableControlModel(config, state_dict)
      File "D:\AI\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\cldm.py", line 24, in __init__
        self.control_model.load_state_dict(state_dict, strict=False)
      File "D:\AI\sd-webui-aki-v4.8\python\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
        raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
    RuntimeError: Error(s) in loading state_dict for ControlNet:
        size mismatch for task_embedding: copying a param with shape torch.Size([8, 320]) from checkpoint, the shape in current model is torch.Size([6, 320]).
        size mismatch for control_add_embedding.linear_1.weight: copying a param with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1536]).

**Comment by xinsir6** [comment]
I will update the sripts now. Wait a minute.

**Comment by alex13by** [comment]
What do I need to do to use this model in comfyui or in webui? Or how does this script work
