### ISSUE TITLE
Error in ComfyUI Startup Log for ControlNetPlus

### ISSUE THREAD

**Issue by camoody1** [xinsir6/ControlNetPlus#27]
After installing ControlNetPlus into Comfy, I am now getting this error in the startup log:

```
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ControlNetPlus\\__init__.py'

Cannot import H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlNetPlus module for custom nodes: [Errno 2] No such file or directory: 'H:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ControlNetPlus\\__init__.py'
```

Any thoughts on how to fix this? I installed your module using the Comfy Manager Install from GitHub Link to install.

Thank you for any assistance.

**Comment by 1419139302** [comment]
I had the same mistake. Did you solve your problem
