### ISSUE TITLE
tile super resolution issue

### ISSUE THREAD

**Issue by HanLiii** [xinsir6/ControlNetPlus#62]
When I try to run controlnet_union_test_tile_super_resolution.py, it occurs following issue:

Traceback (most recent call last):
  File "controlnet_union_test_tile_super_resolution.py", line 15, in <module>
    from pipeline.pipeline_controlnet_union_sd_xl_img2img import StableDiffusionXLControlNetUnionImg2ImgPipeline
  File "/data/hli358/han/ControlNetPlus/promax/../pipeline/pipeline_controlnet_union_sd_xl_img2img.py", line 160, in <module>
    class StableDiffusionXLControlNetUnionImg2ImgPipeline(
  File "/data/hli358/han/ControlNetPlus/promax/../pipeline/pipeline_controlnet_union_sd_xl_img2img.py", line 239, in StableDiffusionXLControlNetUnionImg2ImgPipeline
    controlnet: Union[ControlNetModel, List[ControlNetModel], Tuple[ControlNetModel], MultiControlNetModel],
NameError: name 'ControlNetModel' is not defined

**Comment by djcedr** [comment]
Same here...

**Comment by CristianCuadrado** [comment]
You need to add the following line:

from diffusers.models.controlnet import ControlNetModel
