### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.loaders.single_file_model'

### ISSUE THREAD

**Issue by muzammildafedar** [xinsir6/ControlNetPlus#68]
I went through the instructions for installation. During the Canny run got these errors

```
python controlnet_union_test_canny.py 
Traceback (most recent call last):
  File "controlnet_union_test_canny.py", line 9, in <module>
    from models.controlnet_union import ControlNetModel_Union
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/muzammildafedaar1/code/users/xyz/ControlNetPlus/models/controlnet_union.py", line 22, in <module>
    from diffusers.loaders.single_file_model import FromOriginalModelMixin
ModuleNotFoundError: No module named 'diffusers.loaders.single_file_model'
```

My Diffuser info
```
Name: diffuser
Version: 0.0.1
Summary: 
Home-page: 
Author: 
Author-email: 
License: MIT License
Location: /anaconda/envs/controlplus/lib/python3.8/site-packages
Requires: 
Required-by: 
```

**Comment by muzammildafedar** [comment]
Upgrade the diffuser to 29.2
